VIDEO_WIDTH = 1024
VIDEO_HEIGHT = 600
COUNTER_FOR_ALCOHOL_MEASURING = 10
ERROR_TO_MUCH_TIME_IN_ALCOHOL_CHECK = 100
BASE_URL = "https://node.alkowall.indigoingenium.ba"  # Intentional wrong URL for retry testing
DEVICE_ID = 1
VIDEOS_DIRECTORY = "videos/"
TARGET_PLATFORM_SYSTEM = "linux"
TARGET_PLATFORM_ARCHITECTURE = "x86_644" # Intentional wrong architecture for retry testing x86_64 is real
GIT_URL = "https://github.com/Bojan9597/alcoWall.git"
BRANCH_API_URL = "https://node.alkowall.indigoingenium.ba/status/get_github_branch"
DEVICE_ID_FILE = "device_id.txt"
ALCOHOL_LEVEL_ALLOWED_ERROR = 0.1
TIME_IN_ALCOHOL_CHECKED_STATE_FOR_ALCOHOL_SENSOR_COOLDOWN = 10
ALCOHOL_LEVEL_MEASUREMENT_TIME_INTERVAL = 0.2