VIDEO_WIDTH = 1024
VIDEO_HEIGHT = 600
COUNTER_FOR_ALCOHOL_MEASURING = 1000
ERROR_TO_MUCH_TIME_IN_ALCOHOL_CHECK = 100
BASE_URL = "https://node.alkowall.indigoingenium.ba"  # Intentional wrong URL for retry testing
DEVICE_ID = 1
VIDEOS_DIRECTORY = "Media/videos/"
TARGET_PLATFORM_SYSTEM = "Linux"
TARGET_PLATFORM_ARCHITECTURE = "aarch64" # Intentional wrong architecture for retry testing x86_64 is real
GIT_URL = "https://github.com/Bojan9597/alcoWall.git"
BRANCH_API_URL = "https://node.alkowall.indigoingenium.ba/status/get_github_branch"
DEVICE_ID_FILE = "Constants/device_id.txt"
ALCOHOL_LEVEL_ALLOWED_ERROR = 0.1
TIME_IN_ALCOHOL_CHECKED_STATE_FOR_ALCOHOL_SENSOR_COOLDOWN = 10
ALCOHOL_LEVEL_MEASUREMENT_TIME_INTERVAL = 0.2
PERCENTAGE_OF_SCREEN_WIDTH_THAT_PROXIMITY_SENSOR_TEXT_TAKES = 0.55
